# Generated by Django 4.0.4 on 2023-05-01 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('instagram', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_attach', models.URLField(max_length=400, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('id_people', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_people', to='base_api.peoplemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('number_seats', models.PositiveIntegerField()),
                ('transport_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TripModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(null=True)),
                ('return_date', models.DateTimeField(null=True)),
                ('trip_price', models.FloatField(null=True)),
                ('ticket_price', models.FloatField(null=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_trip', to='base_api.eventmodel')),
                ('id_transport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transport_trip', to='base_api.transportmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
